document.addEventListener('DOMContentLoaded', function() {
	const streets = [
		{ name: "E COSTILLA AVE", group: 3 },
		{ name: "E COSTILLA WAY", group: 2 },
		{ name: "E COUNTY LINE RD", group: 1 },
		{ name: "E DAVIES AVE", group: 2 },
		{ name: "E DRY CREEK PL", group: 2 },
		{ name: "E DRY CREEK RD", group: 2 },
		{ name: "E EASTER AVE", group: 2 },
		{ name: "E EASTER CIR", group: 2 },
		{ name: "E EASTER CIR N", group: 3 },
		{ name: "E EASTER CIR S", group: 3 },
		{ name: "E EASTER DR", group: 3 },
		{ name: "E EASTER PL", group: 3 },
		{ name: "E FREMONT AVE", group: 2 },
		{ name: "E FREMONT CIR N", group: 2 },
		{ name: "E FREMONT DR", group: 3 },
		{ name: "E FREMONT PL", group: 2 },
		{ name: "E GEDDES AVE", group: 3 },
		{ name: "E GEDDES CIR", group: 3 },
		{ name: "E GEDDES DR", group: 3 },
		{ name: "E GEDDES PL", group: 3 },
		{ name: "E HIGHLINE CIR", group: 2 },
		{ name: "E HINSDALE AVE  LITTLTON", group: 2 },
		{ name: "E HINSDALE AVE", group: 3 },
		{ name: "E IRISH LN", group: 1 },
		{ name: "E IRWIN LN", group: 1 },
		{ name: "E KETTLE AVE", group: 1 },
		{ name: "E KETTLE PL", group: 1 },
		{ name: "E LONG PL", group: 1 },
		{ name: "E MINERAL AVE", group: 1 },
		{ name: "E NICHOLS DR", group: 1 },
		{ name: "E NICHOLS PL", group: 1 },
		{ name: "E NOBLES RD", group: 3 },
		{ name: "E NOVA AVE", group: 1 },
		{ name: "E OTERO AVE", group: 1 },
		{ name: "E PHILLIPS AVE", group: 1 },
		{ name: "E PHILLIPS DR ", group: 1 },
		{ name: "E PHILLIPS DR N", group: 1 },
		{ name: "E PHILLIPS DR S", group: 1 },
		{ name: "E PHILLIPS LN", group: 1 },
		{ name: "E PHILLIPS PL", group: 1 },
		{ name: "E STERNE BLVD", group: 2 },
		{ name: "S BROADWAY ", group: 2 },
		{ name: "S CLARKSON ST", group: 2 },
		{ name: "S COOK ST", group: 3 },
		{ name: "S COOK WAY", group: 3 },
		{ name: "S CORONA CT", group: 1 },
		{ name: "S DETROIT CIR", group: 3 },
		{ name: "S DOWNING CIR E", group: 2 },
		{ name: "S DOWNING CIR W", group: 2 },
		{ name: "S DOWNING ST", group: 1 },
		{ name: "S ELIZABETH CIR", group: 3 },
		{ name: "S ELIZABETH ST", group: 3 },
		{ name: "S EMERSON CIR", group: 1 },
		{ name: "S EMERSON WAY", group: 1 },
		{ name: "S FILLMORE CIR", group: 3 },
		{ name: "S FRANKLIN CT", group: 1 },
		{ name: "S FRANKLIN WAY", group: 1 },
		{ name: "S GARFIELD ST", group: 3 },
		{ name: "S GARFIELD WAY", group: 3 },
		{ name: "S GAYLORD CT", group: 1 },
		{ name: "S GAYLORD ST", group: 2 },
		{ name: "S GAYLORD ST A", group: 2 },
		{ name: "S GAYLORD ST H", group: 2 },
		{ name: "S GAYLORD ST I", group: 2 },
		{ name: "S GAYLORD WAY", group: 1 },
		{ name: "S GRANT ST", group: 2 },
		{ name: "S HARRISON CT", group: 3 },
		{ name: "S HARRISON WAY", group: 3 },
		{ name: "S HIGH CT", group: 1 },
		{ name: "S HUMBOLDT ST", group: 1 },
		{ name: "S JACKSON ST", group: 3 },
		{ name: "S KIT CARSON DR", group: 1 },
		{ name: "S LAFAYETTE CIR E", group: 2 },
		{ name: "S LINCOLN WAY", group: 2 },
		{ name: "S LOGAN CT", group: 1 },
		{ name: "S LOGAN DR", group: 1 },
		{ name: "S LOGAN ST", group: 1 },
		{ name: "S MADISON CT", group: 3 },
		{ name: "S MADISON WAY", group: 3 },
		{ name: "S OGDEN CIR", group: 1 },
		{ name: "S OGDEN CT", group: 2 },
		{ name: "S PENNSYLVANIA CT", group: 2 },
		{ name: "S PENNSYLVANIA ST", group: 2 },
		{ name: "S PENROSE CT", group: 2 },
		{ name: "S RACE ST", group: 2 },
		{ name: "S RACE WAY", group: 1 },
		{ name: "S SHERMAN ST", group: 2 },
		{ name: "S STEELE CIR", group: 3 },
		{ name: "S STEELE ST", group: 3 },
		{ name: "S UNIVERSITY BLVD", group: 3 },
		{ name: "S WASHINGTON CIR", group: 2 },
		{ name: "S WASHINGTON ST", group: 2 },
		{ name: "S WELLINGTON ST", group: 2 },
		{ name: "S WILLIAMS WAY", group: 1 },
		{ name: "S YORK CT", group: 1 },
		{ name: "VILLAGE PARK DR", group: 2 },
		{ name: "Village Park Dr unit", group: 2 },
	];
	window.searchStreet = function() {
		const input = document.getElementById('searchInput').value.toUpperCase();
		const results = document.getElementById('results');
		results.innerHTML = ''; // Очистка результатов перед новым поиском

		const filteredStreets = streets.filter(street => street.name.includes(input));

		filteredStreets.forEach(street => {
				const div = document.createElement('div');
				div.innerHTML = `${street.name} <span class="group-number">${street.group}</span>`;
				results.appendChild(div);
		});
	}
})